[package]
name = "glb"
version = "0.1.0"
authors = ["rogermadjos <roger@hov.co>"]
edition = "2018"

[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
log = "0.4"
pretty_env_logger = "0.3"
rand = "0.8"